version: '3'

networks:
  txs_auth: {}

services:

  txs_auth_testing_ldap:
    image: osixia/openldap:1.2.2
    ports:
    - 127.0.0.1:389:389
    - 127.0.0.1:689:689
    environment:
      LDAP_NOFILE: 10000
    volumes:
    - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug
    networks:
      - txs_auth

  txs_auth_testing_postgres:
    image: postgres:11
    ports:
      - 127.0.0.1:5234:5432
    environment:
      POSTGRES_DATABASES: auth
      POSTGRES_USER: auth
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_PASSWORD:
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=200'
    networks:
      - txs_auth


# https://hub.docker.com/r/unicon/shibboleth-idp/
#  shibboleth-idp:
#    image: "unicon/shibboleth-idp"
#    ports:
#    - 8443:8443
#    - 443:4443
#    volumes:
#    - './shibboleth-idp:/ext-mount'

# https://hub.docker.com/r/unicon/shibboleth-sp/
#  shibboleth-sp:
#    image: "unicon/shibboleth-sp"
#    ports:
#    - 80:80
#    - 443:443
