version: '3'
services:
  ldap:
    image: osixia/openldap
    container_name: openldap
    ports:
    - localhost:389:389
    - localhost:689:689
    volumes:
    - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service


# https://hub.docker.com/r/unicon/shibboleth-idp/
#  shibboleth-idp:
#    image: "unicon/shibboleth-idp"
#    ports:
#    - 8443:8443
#    - 443:4443
#    volumes:
#    - './shibboleth-idp:/ext-mount'

# https://hub.docker.com/r/unicon/shibboleth-sp/
#  shibboleth-sp:
#    image: "unicon/shibboleth-sp"
#    ports:
#    - 80:80
#    - 443:443
